### ISSUE TITLE
gpflow.models.GPR documentation: "log marginal likelihood"

### ISSUE THREAD

**Issue by polaschwoebel** [GPflow/docs#4]
Hi all, thanks for your great work on GPflow! 

The documentation for gpflow.models.GPR says: 

"The log likelihood of this model is sometimes referred to as the ‘log marginal likelihood’, and is given by
![$ \log p (y|f) =  \mathcal{N}(y|0,K + \sigma_n I)$](https://render.githubusercontent.com/render/math?math=%24%20%5Clog%20p%20(y%7Cf)%20%3D%20%20%5Cmathcal%7BN%7D(y%7C0%2CK%20%2B%20%5Csigma_n%20I)%24). 

I find this misleading. The function `log_marginal_likelihood(self)` computes the "actual" log marginal likelihood ![\log p(y| \theta)](https://render.githubusercontent.com/render/math?math=%5Clog%20p(y%7C%20%5Ctheta)) - I'd suggest removing "is sometimes referred to as the ‘log marginal likelihood’"?

**Comment by st--** [comment]
Hi @polaschwoebel, thanks for bringing this to our attention! I've only just spotted this issue because this `docs` repository is solely for hosting the auto-generated docs - for next time, please open an issue in the [GPflow/GPflow repository](https://github.com/GPflow/GPflow) repository. You'd be very welcome to contribute your suggestion directly as a pull request. Join us on gpflow.slack.com (invite link in the README.md) if you want to chat about it directly :)
